---
name: Test Ruby code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: bundle exec rubocop
      - uses: aarcangeli/load-dotenv@v1.0.0
        with:
          filenames: .env.example
          if-file-not-found: error
      - run: bundle exec rake test
